### ISSUE TITLE
bug: gaeblogx.com/search/ couldn't appear search box.

### ISSUE THREAD

**Issue by yefeiyu** [SeraphRoy/SeraphRoy.github.io#1]
It's appear in all the explore, but didn't appear on Safari or Chrome of iOS 9.0 , iphone 6s plus.
![1992292266](https://user-images.githubusercontent.com/4845104/37901439-cfc82d4c-3123-11e8-9ad3-09507783289a.jpg)

**Comment by SeraphRoy** [comment]
My guess is that it might be a bug of instantsearch.js provided by Algolia. The front-end search bar is provided by the widget:

```
  7 const search = instantsearch({                                                        
  8   appId: '{{ site.algolia.application_id }}',                                         
  9   apiKey: '{{ site.algolia.search_only_api_key }}',                                   
 10   indexName: '{{ site.algolia.index_name }}',                                         
 11   searchParameters: {                                                                 
 12     restrictSearchableAttributes: [                                                   
 13     ¦ 'title',                                                                        
 14     ¦ 'content'                                                                       
 15     ]                                                                                 
 16   }                                                                                   
 17 }); 
```

```
 37 search.addWidget(                                                                     
 38   instantsearch.widgets.searchBox({                                                   
 39     container: '#search-searchbar',                                                   
 40     placeholder: 'Search into posts...'                                               
 41   })                                                                                  
 42 ); 
```

You can take a look at the codes in [_includes/algolia.html](https://github.com/SeraphRoy/SeraphRoy.github.io/blob/master/_includes/algolia.html)

I only have a guess for now as I am unable to reproduce it on my simulated device for Safari 9.0 on iOS 9.0:
<img width="354" alt="screen shot 2018-03-26 at 8 24 53 am" src="https://user-images.githubusercontent.com/13044821/37916202-1d20894e-30d0-11e8-9950-cbd27263d8cf.png">

It would be great if you can provide me some more information ;)

**Comment by yefeiyu** [comment]
Thank you for your answer.
I will report to instantsearch.js .
